# .github/workflows/enforce-dev-to-main.yml
name: Enforce Dev to Main Merges

on:
  pull_request:
    branches: [ main ]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR comes from dev branch
        if: github.head_ref != 'dev'
        run: |
          echo "❌ PRs to main must come from dev"
          exit 1
